name:           doc-browser
version:        0.6.1
author:         Incomplete
maintainer:     incomplete@aixon.co
copyright:      Incomplete 2018
license:        MPL-2.0
github:         qwfy/doc-browser
synopsis:       A documentation browser
category:       Application
description:    Please see the README on Github at <https://github.com/qwfy/doc-browser#readme>

extra-source-files:
- README.asciidoc

dependencies:
- base >= 4.7 && < 5
- filepath
- containers
- hsqml
- text
- aeson
- bytestring
- warp
- wai
- wai-extra
- binary
- http-types
- network-uri
- stm
- wreq
- lens
- zlib
- tar
- temporary
- directory
- criterion
- deepseq
- regex-pcre
- array
- optparse-applicative
- transformers
- hoogle
- safe
- extra
- async
- lzma
- MissingH
- Hclip
- open-browser
- process
- time
- yaml
- filelock
- unix
- servant-server
- servant-docs
- lens
- path
- path-io
- exceptions
- file-embed
- template-haskell
- persistent
- persistent-sqlite
- persistent-template
- mtl
- either
- uuid
- conduit
- monad-logger
- fmt
- xml-conduit
- xml-lens
- base64-bytestring
- vector
- hashable
- tagsoup
- utf8-string
- shakespeare

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fno-warn-type-defaults
  - -fno-warn-missing-signatures
  - -fno-warn-name-shadowing
  - -Werror
  - -O2

executables:
  doc-browser:
    main: Main.hs
    source-dirs: app
    ghc-options: &exe-ghc-options
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    - -fno-warn-type-defaults
    - -fno-warn-missing-signatures
    - -fno-warn-name-shadowing
    - -Werror
    dependencies: &exe-dependencies
    - doc-browser

benchmarks:
  prof-search:
    main: ProfSearch.hs
    source-dirs: prof
    ghc-options: *exe-ghc-options
    dependencies: *exe-dependencies
